title: "Andrew Pasco"
email: "apascos@gmail.com"
description: "Mechanical Engineer | Robotics & Human–Robot Interaction | MPhil @ Cambridge | MS @ Stanford"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrewpasco.github.io" # your site URL
logo: /assets_headshot.jpg

remote_theme: "jekyll-theme-minimal"

# Author info
author:
  name: "Andrew Pasco"
  email: "apascos@gmail.com"

# Plugins and markdown
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Personal"
    url: /personal/
  - title: "Contact"
    url: /contact/

# Social links
social_links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/AndrewPasco"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/andrew-pasco1/"
  - label: "Email"
    icon: "fa fa-envelope"
    url: "mailto:apascos@gmail.com"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: false
